// Mock data matching the exact shape of Workflow B's response (see CONTRACT.md).
export function getMockDocuments() {
  return [
    {
      "Received At": "2026-08-05T20:34:09.000Z",
      "File Name": "01_invoice_042.pdf",
      "File Link": "https://drive.google.com/file/d/mock1/view",
      "Document Type": "invoice",
      "Sender / Company": "Nordic Office Supplies",
      "Summary": "This invoice from Nordic Office Supplies covers a bulk order of office furniture and stationery delivered last week.",
      "Requested Action": "Payment is due",
      "Deadline": "August 6, 2026",
      "Urgency": "High",
      "Department": "Finance",
      "Status": "Processed",
      "output": "",
      "Document ID": "",
      "Reviewed By": "",
      "Review Note": "",
    },
    {
      "Received At": "2026-08-06T09:15:22.000Z",
      "File Name": "02_contract_renewal.pdf",
      "File Link": "https://drive.google.com/file/d/mock2/view",
      "Document Type": "contract",
      "Sender / Company": "Bright Legal Partners",
      "Summary": "Renewal contract for the annual office lease agreement, requiring signature before the current term expires.",
      "Requested Action": "Review and sign",
      "Deadline": "August 20, 2026",
      "Urgency": "Medium",
      "Department": "Legal",
      "Status": "Needs Review",
      "output": "",
      "Document ID": "",
      "Reviewed By": "",
      "Review Note": "",
    },
    {
      "Received At": "2026-08-07T14:02:47.000Z",
      "File Name": "03_hr_policy_update.docx",
      "File Link": "https://drive.google.com/file/d/mock3/view",
      "Document Type": "policy",
      "Sender / Company": "Internal HR",
      "Summary": "Updated remote-work policy document outlining new eligibility criteria and approval workflow.",
      "Requested Action": "Acknowledge receipt",
      "Deadline": "Not found",
      "Urgency": "Low",
      "Department": "HR",
      "Status": "Processed",
      "output": "",
      "Document ID": "",
      "Reviewed By": "",
      "Review Note": "",
    },
    {
      "Received At": "2026-08-08T11:47:03.000Z",
      "File Name": "04_shipping_notice.pdf",
      "File Link": "https://drive.google.com/file/d/mock4/view",
      "Document Type": "notice",
      "Sender / Company": "Global Freight Co.",
      "Summary": "Shipping notice confirming delayed delivery of hardware order due to customs processing.",
      "Requested Action": "Update procurement team",
      "Deadline": "August 10, 2026",
      "Urgency": "High",
      "Department": "Operations",
      "Status": "Needs Review",
      "output": "",
      "Document ID": "",
      "Reviewed By": "",
      "Review Note": "",
    },
    {
      "Received At": "2026-08-09T08:30:11.000Z",
      "File Name": "05_expense_report.xlsx",
      "File Link": "https://drive.google.com/file/d/mock5/view",
      "Document Type": "report",
      "Sender / Company": "Internal Finance",
      "Summary": "Quarterly expense report summarizing travel and client entertainment costs across departments.",
      "Requested Action": "Approve for filing",
      "Deadline": "Not found",
      "Urgency": "Not found",
      "Department": "Finance",
      "Status": "Processed",
      "output": "",
      "Document ID": "",
      "Reviewed By": "",
      "Review Note": "",
    },
  ];
}
