// Mock data matching the exact shape of Workflow B's response (see CONTRACT.md).
// Free-text fields (Summary, Requested Action, Reviewed By, Review Note) are
// written in Hebrew here since this is mock content only; the field NAMES
// themselves stay exactly as documented in CONTRACT.md.
export function getMockDocuments() {
  return [
    {
      "Received At": "2026-08-05T20:34:09.000Z",
      "File Name": "01_invoice_042.pdf",
      "File Link": "https://drive.google.com/file/d/mock1/view",
      "Document Type": "invoice",
      "Sender / Company": "Nordic Office Supplies",
      "Summary": "חשבונית מחברת Nordic Office Supplies עבור הזמנה מרוכזת של ריהוט משרדי וציוד כתיבה שסופקה בשבוע שעבר.",
      "Requested Action": "יש לבצע תשלום",
      "Deadline": "August 6, 2026",
      "Urgency": "High",
      "Department": "Finance",
      "Status": "Processed",
      "output": "",
      "Document ID": "",
      "Reviewed By": "יעל כהן",
      "Review Note": "אושר לתשלום, תואם להזמנה המקורית.",
    },
    {
      "Received At": "2026-08-06T09:15:22.000Z",
      "File Name": "02_quote_office_chairs.pdf",
      "File Link": "https://drive.google.com/file/d/mock2/view",
      "Document Type": "quote",
      "Sender / Company": "Bright Furniture Ltd.",
      "Summary": "הצעת מחיר לרכישת כיסאות משרדיים חדשים עבור קומת הפיתוח, כולל הנחת כמות.",
      "Requested Action": "יש לבדוק ולאשר את ההצעה",
      "Deadline": "August 20, 2026",
      "Urgency": "Medium",
      "Department": "Procurement",
      "Status": "Needs Review",
      "output": "",
      "Document ID": "",
      "Reviewed By": "",
      "Review Note": "",
    },
    {
      "Received At": "2026-08-07T14:02:47.000Z",
      "File Name": "03_customer_complaint.docx",
      "File Link": "https://drive.google.com/file/d/mock3/view",
      "Document Type": "complaint",
      "Sender / Company": "לקוח: דניאל אברהם",
      "Summary": "תלונת לקוח בנוגע לעיכוב במענה של צוות התמיכה בפנייה בנושא תקלה בשירות.",
      "Requested Action": "יש ליצור קשר עם הלקוח ולסגור את הפנייה",
      "Deadline": "Not found",
      "Urgency": "Low",
      "Department": "Support",
      "Status": "Processed",
      "output": "",
      "Document ID": "",
      "Reviewed By": "אורי לוי",
      "Review Note": "טופל מול הלקוח, הפנייה נסגרה בשביעות רצון.",
    },
    {
      "Received At": "2026-08-08T11:47:03.000Z",
      "File Name": "04_sales_request.pdf",
      "File Link": "https://drive.google.com/file/d/mock4/view",
      "Document Type": "request",
      "Sender / Company": "Global Freight Co.",
      "Summary": "בקשה מלקוח פוטנציאלי לפגישת מכירות והצגת מוצר, כולל בקשה להצעת מחיר ראשונית.",
      "Requested Action": "יש לתאם פגישה עם נציג מכירות",
      "Deadline": "August 10, 2026",
      "Urgency": "High",
      "Department": "Sales",
      "Status": "Needs Review",
      "output": "",
      "Document ID": "",
      "Reviewed By": "",
      "Review Note": "",
    },
    {
      "Received At": "2026-08-09T08:30:11.000Z",
      "File Name": "05_expense_report.xlsx",
      "File Link": "https://drive.google.com/file/d/mock5/view",
      "Document Type": "report",
      "Sender / Company": "Internal Finance",
      "Summary": "דוח הוצאות רבעוני המסכם עלויות נסיעות ואירוח לקוחות בין המחלקות השונות.",
      "Requested Action": "יש לאשר את הדוח לצורך תיוק",
      "Deadline": "Not found",
      "Urgency": "Not found",
      "Department": "General",
      "Status": "Processed",
      "output": "",
      "Document ID": "",
      "Reviewed By": "יעל כהן",
      "Review Note": "נבדק ואושר, ללא חריגות.",
    },
  ];
}
